# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo {c:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/fullAdder.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/mux_2to1.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/ff.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/adderUnit.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/reg_Nbit.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/driver.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/shifter_nBit.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/DataMem.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/ALU.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/ALUcontrolUnit.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/ImmGen.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/controlUnit.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/regFile.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/InstMem.v}
  {C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/sources_1/new/processor.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/farna/Desktop/Labs/Lab 6/exp1/exp1.srcs/constrs_1/new/const.xdc}}]


synth_design -top processor -part xc7a100tcsg324-1


write_checkpoint -force -noxdef processor.dcp

catch { report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb }
