webtalk_init -webtalk_dir C:/Users/Hana Asal/Desktop/Computer Architecture/Project/clone/Processor/vivado/exp1.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 19 23:04:53 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "24e2fd1a-1ae1-4ece-b54f-4e4c9c2d88db" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0c9a0372d921409b9d6f51e7b09de71e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "214" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "19" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "149 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "193 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "4303" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2162" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "63276_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2635224421 -regid "" -xml C:/Users/Hana Asal/Desktop/Computer Architecture/Project/clone/Processor/vivado/exp1.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Hana Asal/Desktop/Computer Architecture/Project/clone/Processor/vivado/exp1.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Hana Asal/Desktop/Computer Architecture/Project/clone/Processor/vivado/exp1.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
