#7 seg display
set_property PACKAGE_PIN T10 [get_ports LED_out[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[6]]
set_property PACKAGE_PIN R10 [get_ports LED_out[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[5]]
set_property PACKAGE_PIN K16 [get_ports LED_out[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[4]]
set_property PACKAGE_PIN K13 [get_ports LED_out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[3]]
set_property PACKAGE_PIN P15 [get_ports LED_out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[2]]
set_property PACKAGE_PIN T11 [get_ports LED_out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[1]]
set_property PACKAGE_PIN L18 [get_ports LED_out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out[0]]

#LEDs
set_property PACKAGE_PIN H17 [get_ports light[0]]
set_property IOSTANDARD LVCMOS33 [get_ports light[0]]
set_property PACKAGE_PIN K15 [get_ports light[1]]
set_property IOSTANDARD LVCMOS33 [get_ports light[1]]
set_property PACKAGE_PIN J13 [get_ports light[2]]
set_property IOSTANDARD LVCMOS33 [get_ports light[2]]
set_property PACKAGE_PIN N14 [get_ports light[3]]
set_property IOSTANDARD LVCMOS33 [get_ports light[3]]
set_property PACKAGE_PIN R18 [get_ports light[4]]
set_property IOSTANDARD LVCMOS33 [get_ports light[4]]
set_property PACKAGE_PIN V17 [get_ports light[5]]
set_property IOSTANDARD LVCMOS33 [get_ports light[5]]
set_property PACKAGE_PIN U17 [get_ports light[6]]
set_property IOSTANDARD LVCMOS33 [get_ports light[6]]
set_property PACKAGE_PIN U16 [get_ports light[7]]
set_property IOSTANDARD LVCMOS33 [get_ports light[7]]
set_property PACKAGE_PIN V16 [get_ports light[8]]
set_property IOSTANDARD LVCMOS33 [get_ports light[8]]
set_property PACKAGE_PIN T15 [get_ports light[9]]
set_property IOSTANDARD LVCMOS33 [get_ports light[9]]
set_property PACKAGE_PIN U14 [get_ports light[10]]
set_property IOSTANDARD LVCMOS33 [get_ports light[10]]
set_property PACKAGE_PIN T16 [get_ports light[11]]
set_property IOSTANDARD LVCMOS33 [get_ports light[11]]
set_property PACKAGE_PIN V15 [get_ports light[12]]
set_property IOSTANDARD LVCMOS33 [get_ports light[12]]
set_property PACKAGE_PIN V14 [get_ports light[13]]
set_property IOSTANDARD LVCMOS33 [get_ports light[13]]
set_property PACKAGE_PIN V12 [get_ports light[14]]
set_property IOSTANDARD LVCMOS33 [get_ports light[14]]
set_property PACKAGE_PIN V11 [get_ports light[15]]
set_property IOSTANDARD LVCMOS33 [get_ports light[15]]


#Pushbutton
set_property PACKAGE_PIN N17 [get_ports push]
set_property IOSTANDARD LVCMOS33 [get_ports push]

#Anodes
set_property PACKAGE_PIN U13 [get_ports  Anode[3]]
set_property IOSTANDARD LVCMOS33 [get_ports  Anode[3]]
set_property PACKAGE_PIN K2 [get_ports  Anode[2]]
set_property IOSTANDARD LVCMOS33 [get_ports  Anode[2]]
set_property PACKAGE_PIN T14 [get_ports  Anode[1]]
set_property IOSTANDARD LVCMOS33 [get_ports  Anode[1]]
set_property PACKAGE_PIN P14 [get_ports  Anode[0]]
set_property IOSTANDARD LVCMOS33 [get_ports  Anode[0]]

#clk 
set_property PACKAGE_PIN E3 [get_ports  clk]
set_property IOSTANDARD LVCMOS33 [get_ports  clk]

#rst
set_property PACKAGE_PIN V10 [get_ports  rst]
set_property IOSTANDARD LVCMOS33 [get_ports  rst]


#Switches
set_property PACKAGE_PIN J15 [get_ports switch[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[0]]
set_property PACKAGE_PIN L16 [get_ports switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[1]]
set_property PACKAGE_PIN M13 [get_ports switch[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[2]]
set_property PACKAGE_PIN R15 [get_ports switch[3]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[3]]
set_property PACKAGE_PIN R17 [get_ports switch[4]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[4]]
set_property PACKAGE_PIN T18 [get_ports switch[5]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[5]]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets push]